Hunger.class: Hunger.java Attribute.class
	javac -g Hunger.java

Mood.class: Mood.java Attribute.class
	javac -g Mood.java

Cleanliness.class: Cleanliness.java Attribute.class
	javac -g Cleanliness.java

Intelligence.class: Intelligence.java Attribute.class
	javac -g Intelligence.java

Dragon.class: Dragon.java Pet.class
	javac -g Dragon.java

Fish.class: Fish.java Pet.class
	javac -g Fish.java

Pig.class: Pig.java Pet.class
	javac -g Pig.java

Attribute.class: Attribute.java
	javac -g Attribute.java

Pet.class: Pet.java
	javac -g Pet.java

Runner.class: Runner.java
	javac -g Runner.java

clean:
	rm *.class

run: Runner.class
	java Runner
